server:
  port: 8081

spring:
  application:
    name: rest-gateway
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.springframework: ERROR
    com.cupshe: DEBUG
