server:
  port: 7777

spring:
  main:
    allow-bean-definition-overriding: true
    banner-mode: off
  application:
    name: rest-gateway
  profiles:
    active: dev

logging:
  level:
    org.springframework: ERROR
    reactor.netty: ERROR
    com.cupshe: DEBUG
